// Add a new entry here whenever a new game ships. The hub page and the
// sidebar both read from this list, so nothing else needs to change.
export const games = [
  {
    slug: 'wordle',
    href: '/wordle',
    title: 'وردل فارسی',
    tagline: 'یک کلمه، شش تلاش، هر روز ساعت ۹ شب',
    icon: '🟩',
    status: 'live', // 'live' | 'soon'
  },
  {
    slug: 'factle',
    href: '/factle',
    title: 'فکتل',
    tagline: 'یک کشور ، شش سرنخ، هر روز ساعت ۹ شب',
    icon: '🌍',
    status: 'live',
  },
  {
    slug: 'colordle',
    href: '/colordle',
    title: 'رنگدل',
    tagline: 'یک رنگ ، با اسلایدرها بسازش ، هر روز ساعت ۹ شب',
    icon: '🎨',
    status: 'live',
  },
  {
    slug: 'mordle',
    href: '/mordle',
    title: 'موردل',
    tagline: 'هر روز ۵ سوال، کدوم عدد بزرگ‌تره؟ هر روز ساعت ۹ شب',
    icon: '⚖️',
    status: 'live',
  },
  {
    slug: 'moneydle',
    href: '/moneydle',
    title: 'پولدل',
    tagline: 'هر روز ۵ ارز، از باارزش تا کم‌ارزش مرتبشون کن، هر روز ساعت ۹ شب',
    icon: '💰',
    status: 'live',
  },
  {
    slug: 'goldle',
    href: '/goldle',
    title: 'طلادل',
    tagline: 'با ۱۰۰ طلا شروع کن، رو جواب درست شرط ببند، هر روز ساعت ۹ شب',
    icon: '🪙',
    status: 'live',
  },
  {
    slug: 'chordle',
    href: '/chordle',
    title: 'کوردل',
    tagline: 'نت‌های پیانو رو بشنو و ترتیبشو درست بساز، هر روز ساعت ۹ شب',
    icon: '🎹',
    status: 'live',
  },
  {
    slug: 'pricedle',
    href: '/pricedle',
    title: 'قیمتدل',
    tagline: 'قیمت چیزهای مختلف رو در سال‌های گذشته حدس بزن، هر روز ساعت ۹ شب',
    icon: '🧾',
    status: 'live',
  },
  {
    slug: 'memorydle',
    href: '/memorydle',
    title: 'مموریدل',
    tagline: '۵ عدد رو به خاطر بسپار، از بین ۱۵ پیداشون کن، هر روز ساعت ۹ شب',
    icon: '🧠',
    status: 'live',
  },
  {
    slug: 'crossword',
    href: '/crossword',
    title: 'مینی جدول',
    tagline: 'جدول‌های کلمات فارسی — باز کن و حل کن',
    icon: '🔠',
    status: 'live',
  },
];